repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c "source .env.test && poetry run pytest tests"
        language: system
        pass_filenames: false
        always_run: true
