"""Add ai sticker reward id to settings

Revision ID: 05836fed73a0
Revises: 276858645260
Create Date: 2026-02-09 18:15:19.238423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05836fed73a0'
down_revision: Union[str, Sequence[str], None] = '276858645260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('ai_sticker_reward_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'ai_sticker_reward_id')
    # ### end Alembic commands ###
