"""Add coins count

Revision ID: 068321f1996f
Revises: 4daf227758f9
Create Date: 2025-07-22 16:48:03.502750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068321f1996f'
down_revision: Union[str, Sequence[str], None] = '4daf227758f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memealerts_settings', sa.Column('coins_for_reward', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memealerts_settings', 'coins_for_reward')
    # ### end Alembic commands ###
