"""Add links to tt and yt

Revision ID: 19c7b255bfa3
Revises: c9f1fa2629dd
Create Date: 2026-06-21 12:48:13.428694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c7b255bfa3'
down_revision: Union[str, Sequence[str], None] = 'c9f1fa2629dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('enable_tiktok_link', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('enable_youtube_link', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'enable_youtube_link')
    op.drop_column('twitch_user_settings', 'enable_tiktok_link')
    # ### end Alembic commands ###
