"""Fix some constrains

Revision ID: 1a876c5c1a91
Revises: fc2350890e46
Create Date: 2025-07-28 22:52:35.705673

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a876c5c1a91'
down_revision: Union[str, Sequence[str], None] = 'fc2350890e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitch_bot_users', 'twitch_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('twitch_bot_users', 'login_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('twitch_bot_users', 'profile_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('twitch_bot_users', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('twitch_bot_users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_twitch_bot_users_login_name'), 'twitch_bot_users', ['login_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitch_bot_users_login_name'), table_name='twitch_bot_users')
    op.alter_column('twitch_bot_users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('twitch_bot_users', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('twitch_bot_users', 'profile_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('twitch_bot_users', 'login_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('twitch_bot_users', 'twitch_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
