"""Add more commands

Revision ID: 38f67940c905
Revises: afee89f89b8f
Create Date: 2025-07-23 22:54:17.391367

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38f67940c905'
down_revision: Union[str, Sequence[str], None] = 'afee89f89b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('enable_bite', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_lick', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_boop', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_pat', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_banana', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_whoami', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_lurk', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_riot', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_pants', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_pyramid', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('twitch_user_settings', sa.Column('enable_pyramid_breaker', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('twitch_user_settings', 'enable_random')
    op.drop_column('twitch_user_settings', 'enable_help')
    op.drop_column('twitch_user_settings', 'enable_fruit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('enable_fruit', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('twitch_user_settings', sa.Column('enable_help', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('twitch_user_settings', sa.Column('enable_random', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('twitch_user_settings', 'enable_pyramid_breaker')
    op.drop_column('twitch_user_settings', 'enable_pyramid')
    op.drop_column('twitch_user_settings', 'enable_pants')
    op.drop_column('twitch_user_settings', 'enable_riot')
    op.drop_column('twitch_user_settings', 'enable_lurk')
    op.drop_column('twitch_user_settings', 'enable_whoami')
    op.drop_column('twitch_user_settings', 'enable_banana')
    op.drop_column('twitch_user_settings', 'enable_pat')
    op.drop_column('twitch_user_settings', 'enable_boop')
    op.drop_column('twitch_user_settings', 'enable_lick')
    op.drop_column('twitch_user_settings', 'enable_bite')
    # ### end Alembic commands ###
