"""Update AI stickers settings

Revision ID: 492cf52bc513
Revises: 5efc3d960b84
Create Date: 2026-07-17 20:19:09.588231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492cf52bc513'
down_revision: Union[str, Sequence[str], None] = '5efc3d960b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('ai_reference_allow_on_other_channels', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'ai_reference_allow_on_other_channels')
    # ### end Alembic commands ###
