"""Add supporters

Revision ID: 4daf227758f9
Revises: b069b4c5b500
Create Date: 2025-07-20 04:15:26.203773

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4daf227758f9'
down_revision: Union[str, Sequence[str], None] = 'b069b4c5b500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memealerts_supporters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memealerts_supporters_id'), 'memealerts_supporters', ['id'], unique=False)
    op.create_index(op.f('ix_memealerts_supporters_link'), 'memealerts_supporters', ['link'], unique=False)
    op.create_index(op.f('ix_memealerts_supporters_name'), 'memealerts_supporters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memealerts_supporters_name'), table_name='memealerts_supporters')
    op.drop_index(op.f('ix_memealerts_supporters_link'), table_name='memealerts_supporters')
    op.drop_index(op.f('ix_memealerts_supporters_id'), table_name='memealerts_supporters')
    op.drop_table('memealerts_supporters')
    # ### end Alembic commands ###
