"""Update generated sticker table with file_id, shown_at and cost

Revision ID: 551c4c14e190
Revises: b7b5e3d6f5a1
Create Date: 2026-05-06 01:26:17.500269

"""
from typing import Sequence, Union
from uuid import uuid4, UUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551c4c14e190'
down_revision: Union[str, Sequence[str], None] = 'b7b5e3d6f5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_image', sa.Column('file_id', sa.UUID(), server_default=str(UUID(int=0)), nullable=False))
    op.add_column('generated_image', sa.Column('shown_at', sa.DateTime(), nullable=True))
    op.add_column('generated_image', sa.Column('cost', sa.Float(), server_default='0', nullable=False))
    op.alter_column('generated_image', 'image',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_image', 'cost')
    op.drop_column('generated_image', 'shown_at')
    op.drop_column('generated_image', 'file_id')
    op.alter_column('generated_image', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
