"""Add user balance

Revision ID: 5752ecd4449a
Revises: 551c4c14e190
Create Date: 2026-05-09 19:45:35.601214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5752ecd4449a'
down_revision: Union[str, Sequence[str], None] = '551c4c14e190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_generated_image_created_at'), 'generated_image', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_image_on_channel'), 'generated_image', ['on_channel'], unique=False)
    op.add_column('twitch_bot_users', sa.Column('total_deposited', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('twitch_bot_users', sa.Column('total_spent', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('twitch_bot_users', sa.Column('balance', sa.Numeric(precision=12, scale=2), sa.Computed('total_deposited - total_spent', ), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_bot_users', 'balance')
    op.drop_column('twitch_bot_users', 'total_spent')
    op.drop_column('twitch_bot_users', 'total_deposited')
    op.drop_index(op.f('ix_generated_image_on_channel'), table_name='generated_image')
    op.drop_index(op.f('ix_generated_image_created_at'), table_name='generated_image')
    # ### end Alembic commands ###
