"""Add AI sticker settings

Revision ID: 5efc3d960b84
Revises: 6af5e257d780
Create Date: 2026-07-17 18:24:56.690188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efc3d960b84'
down_revision: Union[str, Sequence[str], None] = '6af5e257d780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('ai_stickers_show_in_profile', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('twitch_user_settings', sa.Column('ai_reference_show_in_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('ai_sticker_model', sa.String(), server_default='quality', nullable=False))
    op.add_column('twitch_user_settings', sa.Column('ai_reference_usage_policy', sa.String(), server_default='with_my_character', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'ai_reference_usage_policy')
    op.drop_column('twitch_user_settings', 'ai_sticker_model')
    op.drop_column('twitch_user_settings', 'ai_reference_show_in_profile')
    op.drop_column('twitch_user_settings', 'ai_stickers_show_in_profile')
    # ### end Alembic commands ###
