"""Add feed treat and pasta

Revision ID: 6817e6575d1e
Revises: 7fc59a9c8668
Create Date: 2026-02-09 14:41:59.793430

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.models import RaidPasta

# revision identifiers, used by Alembic.
revision: str = '6817e6575d1e'
down_revision: Union[str, Sequence[str], None] = '7fc59a9c8668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch_pasta',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        RaidPasta.__table__,
        [
            {
                'id': uuid.uuid4(),
                'text': 'внезапное 🍺 распитие 🍺 пива 🍺 в 🍺 чате 🍺внезапное 🍺 распитие 🍺 пива 🍺 в 🍺 чате 🍺внезапное 🍺 распитие 🍺 пива 🍺 в 🍺 чате 🍺внезапное 🍺 распитие 🍺 пива 🍺 в 🍺 чате 🍺внезапное 🍺 распитие 🍺 пива 🍺 в 🍺 чате 🍺внезапное 🍺 распитие 🍺 пива 🍺 в 🍺 чате 🍺',
            },
            {
                'id': uuid.uuid4(),
                'text': 'О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc О ВЕЛИКИЙ СУП НАВАРИЛИ SMOrc',
            },
            {
                'id': uuid.uuid4(),
                'text': 'РЕЙД БЕЗ ПАСТЫ!!! pastaThat pastaThat pastaThat pastaThat pastaThat РЕЙД БЕЗ ПАСТЫ!!! pastaThat pastaThat pastaThat pastaThat pastaThat РЕЙД БЕЗ ПАСТЫ!!! pastaThat pastaThat pastaThat pastaThat pastaThat РЕЙД БЕЗ ПАСТЫ!!! pastaThat pastaThat pastaThat pastaThat pastaThat',
            },
            {
                'id': uuid.uuid4(),
                'text': 'AlienPls3 AlienPls3 AlienPls3 AlienPls3 AlienPls3 AlienPls3 AlienPls3 AlienPls3 AlienPls3 ',
            },
            {
                'id': uuid.uuid4(),
                'text': '⠀⢠⣒⣤⠤⣀⣀⠀ ⠀⠀⠠⣒⢤⠋⠂⠈⡷⠒⠒⣗⠢⡀⠀⠀⠀⠀ ⠀⢠⠋⠀⡇⠀⠀⣰⠁⠀⢀⡼⠠⣱⠀⠀⠀⠀ ⠀⢈⠀⠀⣧⣀⣠⣏⢀⠴⠋⠉⠙⡟⡄⠀⠀⠀ ⠀⠘⣄⢠⠟⠉⠉⢻⡎⠀⠀⠀⣸⠇⢸⠀⠀⠀ ⠀⢀⠜⡏⠁⠀⠀⠀⣧⣀⣠⠾⠋⠀⡜⠀⠀⠀ ⠀⡜⠀⠁⠀⠀⠀⠀⠘⣷⠀⠀⡠⠊⠀⠀⠀⠀ ⠀⠹⣁⡤⢾⡀⠀⠀⢠⠏⠀⡐⠁⠀⠀⠀⠀⠀ ⠀⠀⠃⢴⠀⠉⠒⠚⠃⠀⢠⠁⠀⠀⠀⠀⠀⠀ ⠀⢸⠀⠈⠁⠀⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠀ ⠀⢸⠀⠀⠀⠀⠀⠀⠀⢠⠁⠀⠀⠀⠀⠀⠀⠀ ⠀⠸⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠤⠤⠤⠤⠤⠤⠤⠤⠀',
            },
        ],
    )

    op.add_column('twitch_user_settings', sa.Column('enable_pasta', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('enable_feed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('enable_treat', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'enable_treat')
    op.drop_column('twitch_user_settings', 'enable_feed')
    op.drop_column('twitch_user_settings', 'enable_pasta')
    op.drop_table('twitch_pasta')
    # ### end Alembic commands ###
