"""Memealerts oauth upd

Revision ID: 6af5e257d780
Revises: f24c3b6f49cb
Create Date: 2026-06-27 22:20:58.679984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af5e257d780'
down_revision: Union[str, Sequence[str], None] = 'f24c3b6f49cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memealerts_settings', sa.Column('token_refresh_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memealerts_settings', 'token_refresh_expires_at')
    # ### end Alembic commands ###
