"""Add MA currency_name_declensions

Revision ID: 6ef0f77e971a
Revises: b49d6c5ad5ac
Create Date: 2026-06-03 02:30:01.768615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef0f77e971a'
down_revision: Union[str, Sequence[str], None] = 'b49d6c5ad5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memealerts_settings', sa.Column('memecoin_name_genitive', sa.String(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('memecoin_name_accusative', sa.String(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('memecoin_name_genitive_multiple', sa.String(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('memecoin_name_accusative_multiple', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memealerts_settings', 'memecoin_name_accusative_multiple')
    op.drop_column('memealerts_settings', 'memecoin_name_genitive_multiple')
    op.drop_column('memealerts_settings', 'memecoin_name_accusative')
    op.drop_column('memealerts_settings', 'memecoin_name_genitive')
    # ### end Alembic commands ###
