"""Add Generated Images cache

Revision ID: 7fc59a9c8668
Revises: d36a08db1931
Create Date: 2026-02-01 18:28:35.872187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc59a9c8668'
down_revision: Union[str, Sequence[str], None] = 'd36a08db1931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('by_chatter', sa.String(), nullable=False),
    sa.Column('on_channel', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_image_prompt'), 'generated_image', ['prompt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_image_prompt'), table_name='generated_image')
    op.drop_table('generated_image')
    # ### end Alembic commands ###
