"""User likes

Revision ID: 86bccfd8c6af
Revises: c43f8b5f0651
Create Date: 2026-09-21 00:02:27.790284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bccfd8c6af'
down_revision: Union[str, Sequence[str], None] = 'c43f8b5f0651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_user_id <> to_user_id', name='ck_user_likes_not_self'),
    sa.ForeignKeyConstraint(['from_user_id'], ['twitch_bot_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['twitch_bot_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_user_id', 'to_user_id', name='pk_user_likes')
    )
    op.create_index('ix_user_likes_from_user_id', 'user_likes', ['from_user_id'], unique=False)
    op.create_index('ix_user_likes_to_user_id', 'user_likes', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_likes_to_user_id', table_name='user_likes')
    op.drop_index('ix_user_likes_from_user_id', table_name='user_likes')
    op.drop_table('user_likes')
    # ### end Alembic commands ###
