"""Ref moderation

Revision ID: aef7a7240053
Revises: 86bccfd8c6af
Create Date: 2026-09-21 00:40:04.771026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef7a7240053'
down_revision: Union[str, Sequence[str], None] = '86bccfd8c6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_info', sa.Column('approved', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('character_info', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('character_info', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_character_info_updated_at'), 'character_info', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_info_updated_at'), table_name='character_info')
    op.drop_column('character_info', 'updated_at')
    op.drop_column('character_info', 'created_at')
    op.drop_column('character_info', 'approved')
    # ### end Alembic commands ###
