"""Add tg and ds

Revision ID: aef806c55ba8
Revises: dd15c348d6f6
Create Date: 2026-04-09 22:12:28.037854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef806c55ba8'
down_revision: Union[str, Sequence[str], None] = 'dd15c348d6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('enable_tg_link', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('enable_ds_link', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('tg_link', sa.String(), nullable=True))
    op.add_column('twitch_user_settings', sa.Column('ds_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'ds_link')
    op.drop_column('twitch_user_settings', 'tg_link')
    op.drop_column('twitch_user_settings', 'enable_ds_link')
    op.drop_column('twitch_user_settings', 'enable_tg_link')
    # ### end Alembic commands ###
