"""Add beta and followers

Revision ID: afee89f89b8f
Revises: 068321f1996f
Create Date: 2025-07-23 02:50:19.324665

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'afee89f89b8f'
down_revision: Union[str, Sequence[str], None] = '068321f1996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_bot_users', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('twitch_bot_users', sa.Column('in_beta_test', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_bot_users', 'in_beta_test')
    op.drop_column('twitch_bot_users', 'followers_count')
    # ### end Alembic commands ###
