"""Add MA link

Revision ID: b49d6c5ad5ac
Revises: dac2c35b2e38
Create Date: 2026-06-03 01:56:05.354289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49d6c5ad5ac'
down_revision: Union[str, Sequence[str], None] = 'dac2c35b2e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('memealerts_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'memealerts_link')
    # ### end Alembic commands ###
