"""Add chatbot_default_target_behaviour and allow_shared_chat

Revision ID: b7b5e3d6f5a1
Revises: aef806c55ba8
Create Date: 2026-05-01 21:11:39.768757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b5e3d6f5a1'
down_revision: Union[str, Sequence[str], None] = 'aef806c55ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('allow_shared_chat', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('twitch_user_settings', sa.Column('chatbot_default_target_behaviour', sa.String(), server_default='tip', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'chatbot_default_target_behaviour')
    op.drop_column('twitch_user_settings', 'allow_shared_chat')
    # ### end Alembic commands ###
