"""Move links to  table

Revision ID: c9f1fa2629dd
Revises: 6ef0f77e971a
Create Date: 2026-06-21 12:07:29.849194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f1fa2629dd'
down_revision: Union[str, Sequence[str], None] = '6ef0f77e971a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('memealerts', sa.String(), nullable=True),
    sa.Column('tiktok', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['twitch_bot_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)

    op.execute("""
        INSERT INTO links (id, user_id, telegram, discord)
        SELECT id, user_id, tg_link, ds_link
        FROM twitch_user_settings
    """)
        # WHERE tg_link IS NOT NULL OR yt_link IS NOT NULL;
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE twitch_user_settings s
        SET tg_link = l.telegram, ds_link = l.discord
        FROM links l
        WHERE s.id = l.id;
    """)

    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
