"""user cookie consent and boosty tracking

Revision ID: cd92d500ee31
Revises: 1ae68b9b0493
Create Date: 2026-08-30 13:58:50.061149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd92d500ee31'
down_revision: Union[str, Sequence[str], None] = '1ae68b9b0493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_bot_users', sa.Column('cookie_consent_at', sa.DateTime(), nullable=True))
    op.add_column('twitch_bot_users', sa.Column('boosty_dismissed_at', sa.DateTime(), nullable=True))
    op.add_column('twitch_bot_users', sa.Column('boosty_clicks', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_bot_users', 'boosty_clicks')
    op.drop_column('twitch_bot_users', 'boosty_dismissed_at')
    op.drop_column('twitch_bot_users', 'cookie_consent_at')
    # ### end Alembic commands ###
