"""Upd settings

Revision ID: d36a08db1931
Revises: a6e0792566da
Create Date: 2025-12-20 18:49:58.737329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36a08db1931'
down_revision: Union[str, Sequence[str], None] = 'a6e0792566da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pants_deny',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('twitch_user_settings', sa.Column('enable_bonk', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'enable_bonk')
    op.drop_table('pants_deny')
    # ### end Alembic commands ###
