"""Upd index for MA

Revision ID: dac2c35b2e38
Revises: 365262eac1fa
Create Date: 2026-05-15 15:50:37.039946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac2c35b2e38'
down_revision: Union[str, Sequence[str], None] = '365262eac1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_memealerts_supporters_lower_link', 'memealerts_supporters', [sa.literal_column('lower(link)')], unique=False)
    op.create_index('idx_memealerts_supporters_lower_name', 'memealerts_supporters', [sa.literal_column('lower(name)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memealerts_supporters_lower_name', table_name='memealerts_supporters')
    op.drop_index('idx_memealerts_supporters_lower_link', table_name='memealerts_supporters')
    # ### end Alembic commands ###
