"""Add last interaction date to users model

Revision ID: dd15c348d6f6
Revises: 05836fed73a0
Create Date: 2026-04-05 16:22:58.311942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd15c348d6f6'
down_revision: Union[str, Sequence[str], None] = '05836fed73a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_bot_users', sa.Column('interacted_at', sa.DateTime(), server_default='2026-01-01 00:00:00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_bot_users', 'interacted_at')
    # ### end Alembic commands ###
