"""Add enable_bot

Revision ID: e3996e8a002c
Revises: 38f67940c905
Create Date: 2025-07-23 23:18:41.494590

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3996e8a002c'
down_revision: Union[str, Sequence[str], None] = '38f67940c905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('enable_chat_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'enable_chat_bot')
    # ### end Alembic commands ###
