"""Add auto shoutout on raid

Revision ID: e5b36658a27b
Revises: c9b3f413f836
Create Date: 2025-08-02 05:11:36.840883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b36658a27b'
down_revision: Union[str, Sequence[str], None] = 'c9b3f413f836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_user_settings', sa.Column('enable_shoutout_on_raid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_user_settings', 'enable_shoutout_on_raid')
    # ### end Alembic commands ###
