"""Memealerts oauth

Revision ID: f24c3b6f49cb
Revises: 19c7b255bfa3
Create Date: 2026-06-26 02:59:33.446470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24c3b6f49cb'
down_revision: Union[str, Sequence[str], None] = '19c7b255bfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memealerts_settings', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('token_created_at', sa.DateTime(), nullable=True))
    op.add_column('memealerts_settings', sa.Column('token_scopes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memealerts_settings', 'token_scopes')
    op.drop_column('memealerts_settings', 'token_created_at')
    op.drop_column('memealerts_settings', 'token_expires_at')
    op.drop_column('memealerts_settings', 'refresh_token')
    op.drop_column('memealerts_settings', 'access_token')
    # ### end Alembic commands ###
